version: '3'
services:
  myapp_practica:
    build: .
    container_name: myapp_practica
    networks:
    - network_practica
    ports:
    - '83:3000'
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    networks:
    - network_practica
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - myapp_practica
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    networks:
    - network_practica
    ports:
    - "3500:3000"
    volumes:
    - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - myGrafanaVol:/var/lib/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: grafana-clock-panel 1.0.1
    depends_on:
    - prometheus
volumes:
  myGrafanaVol:
networks:
  network_practica: